avatar: /image/IMG_0125.JPG # ç½‘ç«™ Logo
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
    path: /image/LucidDreaam.jpg
    width: 1280
    height: 720
favicon:
    href: /image/ym.png # ç½‘ç«™å›¾æ ‡
    type: image/png # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://kira.host/hexo/config/icon.html
# iconlib: //at.alicdn.com/t/font_3299330_el19bsi97h8.css

cdn: # è¿™é‡Œå¯ä»¥ä¿®æ”¹ç«™ç‚¹ä½¿ç”¨çš„åº“çš„CDN
    gitalk:
        css: https://unpkg.com/gitalk@latest/dist/gitalk.css
        js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
    giscus:
        js: https://giscus.app/client.js


menu:
    å›åˆ°é¦–é¡µ:
        - /
        - icon-home
    æ–‡ç« å½’æ¡£:
        - /pages/archive/
        - icon-container
    å…³äºæœ¬äºº:
        - /pages/mine/
        - icon-user
    æˆ‘çš„æœ‹å‹:
        - /pages/friends/
        - icon-team

widgets:
    - social
    - category
    - archive
    - tagcloud

maxTagcloud: 0 # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶

social:
    QQ:
        - tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=<å»æ‰å°–æ‹¬å·åå¡«ä¸Šä½ çš„QQå·>&website=www.oicqzone.com
        - icon-QQ
        - rgb(49, 174, 255)
        - rgba(49, 174, 255, .1)
    å“”å“©å“”å“©:
        - https://space.bilibili.com/1697331229/<æ”¹æˆä½ çš„Bç«™uid>
        - icon-bilibili
        - rgb(231, 106, 141)
        - rgba(231, 106, 141, .15)
    GitHub:
        - https://github.com/roverstargazer1-max/<ä½ çš„github id>/
        - icon-github
        - rgb(25, 23, 23)
        - rgba(25, 23, 23, .15)
    Gitee:
        - https://gitee.com/<ä½ çš„gitee id>
        - icon-gitee
        - rgb(165, 15, 15)
        - rgba(165, 15, 15, .15)

color: # é…è‰²æ–¹æ¡ˆï¼Œä»firståˆ°seventhä¸ºä¼˜å…ˆçº§ä¸º1-7çš„é¢œè‰²ï¼Œé»˜è®¤ä¸ºå½©è™¹é…è‰²
    first: # åŒæ—¶ä½œä¸ºä¸»é¢˜è‰²
        r: 49
        g: 174
        b: 255
    second:
        r: 255
        g: 78
        b: 106
    third:
        r: 255
        g: 185
        b: 0
    fourth:
        r: 51
        g: 213
        b: 122
    fifth:
        r: 0
        g: 219
        b: 255
    sixth:
        r: 255
        g: 69
        b: 0
    seventh:
        r: 144
        g: 144
        b: 255

# è¯„è®ºåŒº
gitalk:
    active: false # æ˜¯å¦å¯ç”¨ gitalk
    admin: -your github username- # æ‹¥æœ‰å¯¹è¯¥repoè¿›è¡Œæ“ä½œçš„ GitHub username
    owner: -your github username- # æŒæœ‰è¯¥ repo çš„ GitHub username
    repo: -issue repo name- # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
    clientID: -id- # GitHub Client ID
    clientSecret: -key- # GitHub Client Secret
    title: '' # Gitalk Issue Title
# ä½ ä»¬ä¸è¦åœ¨è¿™é‡Œå¡«æˆ‘çš„ giscus é…ç½®é¡¹ï¼Œä¸ç„¶ä½ ä»¬åšå®¢ä¸‹çš„è¯„è®ºä¼šå…¨éƒ¨è·‘åˆ°æˆ‘çš„ä»“åº“ä¸‹é¢â€¦â€¦
# https://giscus.app/zh-CN å¯ä»¥åœ¨è¿™ä¸ªç½‘ç«™ä¸Šæ‰‹åŠ¨é€‰æ‹©é…ç½®å¡«åˆ°ä¸‹æ–¹å¯¹åº”ä½ç½®
giscus:
    active: false # æ˜¯å¦å¯ç”¨ giscus
    repo: -your github username-/-your giscus repo- # å­˜æ”¾è¯„è®ºçš„ discus æ‰€åœ¨çš„ repo
    repoID: -your giscus repo ID- # GitHub repo ID
    category: Announcements # é€‰æ‹©æ–° discussions æ‰€åœ¨çš„åˆ†ç±»
    categoryID: -giscus category id- # åˆ†ç±» ID
    mapping: pathname # pathname, url, title, og:title, specific, number
    # term: # abc 123 # specific | number
    theme: light
    lang: en

copyright: '<strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯'
copyTip: "è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚\nå•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚\næ¥æºï¼š%url" # è‡ªå®šä¹‰å¤åˆ¶ç‰ˆæƒæ–‡æ¡ˆ,ä½¿ç”¨ %url ä»£æ›¿å½“å‰é¡µé¢URL, ä¿®æ”¹ä¸ºfalseç¦ç”¨

# è‡ªå®šä¹‰ä¾§è¾¹æ å°¾éƒ¨å†…å®¹
sidebar: ''

# è‡ªå®šä¹‰æ ·å¼
# customStyles:
#     - style_friends.css


# å‹é“¾é…ç½®
friends:
    - avatar: /image/eliadoarias.png
      link:  https://eliadoarias.top/
      name:  eliadoarias
      desc:  å®‰æ…•å¸Œç—´è’¸é¹…å¿ƒ
    - avatar: /image/b4b722e792e464e8a75528fb1585ecb3.png
      link:  https://zheyi.in/
      name:  æŠ˜ä¹™
      desc:  æ­»å®…è’¸é¹…å¿ƒ
    - avatar: /image/yyz.jpg
      link:  https://endercrysta2.xyz/
      name:  EnderCrysta2
      desc:  TouHouç—´
    - avatar: /image/logo2.jpg
      link:  https://www.h2so4.site/
      name:  H2SO4C
      desc:  ğŸ¤”,cklé¢†åŸŸå¤§ç¥
# å¯å¤åˆ¶çš„ä»£ç å—
copyableCodeblock: true

